using System.Collections;
using System.Collections.Generic;
using UnityEngine;


[RequireComponent(typeof(Rigidbody))]
public class SphereScript : MonoBehaviour
{
    //enum of possible velocity types for the spheres
    public enum CubeMovement
    {
        towardsPlayer,
        awayFromPlayer,
        nothing
    }

    private CubeMovement currentMoveState = CubeMovement.nothing;

    private Rigidbody rigid;

    private PlayerController player;

    private float pullForce;

    private string OniiChan;

    private float gravitationConstant;

    private float Mass;

    private float massPlayer;

    private float earthSimulationMultiplier;

    private void Start()
    {
        //----setting up basic variables and components for later calculations 
        rigid = GetComponent<Rigidbody>();
        player = GameObject.FindGameObjectWithTag("Player").GetComponent<PlayerController>();
        gravitationConstant = 6.672f * (float)Mathf.Pow(10, -11);
        OniiChan = rigid.gameObject + ("chan");
        Mass = rigid.mass;
        earthSimulationMultiplier = Mathf.Pow(10, 10);
        Debug.Log(OniiChan);
    }

    //----velocity generated by gravity is applied every frame
    private void Update()
    {
        ApplyMovement();
    }

    //----gets called when magnet mode is activated by player, applies Forces to calculate velocity/gravity
    public void ChangeMovement(CubeMovement cubeM, float pullForce, float massPlayer)
    {
        this.pullForce = pullForce;
        this.massPlayer = massPlayer;
        currentMoveState = cubeM;
    }
    private void ApplyMovement()
    {
        //----uses players gravity to calculate new velocity for spheres
        Vector3 PullVector = (player.transform.position - transform.position).normalized * CalculateGravitationForce();
        //Debug.Log($"pullVector: {PullVector}");
        //----applies Velocity depending on players magnet mode to sphere
        switch (currentMoveState)
        {
            case CubeMovement.awayFromPlayer:
                rigid.AddForce(-PullVector, ForceMode.Impulse);
                break;
            case CubeMovement.towardsPlayer:
                rigid.AddForce(PullVector, ForceMode.Impulse);
                break;
            case CubeMovement.nothing:
                break;
            default:
                Debug.LogWarning($"undefined cubemovement: {currentMoveState}");
                break;
        }
    }

    //----calculates players gravity in magnet mode
    private float CalculateGravitationForce()
    {
        //Debug.Log($"GravityForce: {((gravitationConstant * Mass * massPlayer * earthSimulationMultiplier) / (player.transform.position - transform.position).magnitude) * pullForce}");
        return ((gravitationConstant * Mass * massPlayer * earthSimulationMultiplier) / (player.transform.position - transform.position).magnitude) * pullForce;
    }

    //----needed to properly subscribe to magnet event
    private void OnEnable()
    {
        PlayerController.OnPlayerCall += ChangeMovement;
    }

    private void OnDisable()
    {
        PlayerController.OnPlayerCall -= ChangeMovement;
    }
}
